### ISSUE TITLE
SSH / Heartbeat

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#10]
Under what circumstances will a node controller continue to heartbeat Wagman but not be reachable via SSH?

**Comment by seanshahkarami** [comment]
As with the modem, the heartbeat doesn't currently depend on the SSH tunnel.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #19](https://github.com/waggle-sensor/development/issues/19) via [**ZenHub**](https://www.zenhub.com/)
