### ISSUE TITLE
Fail Safe Flag for Bootloader in EEPROM

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#12]
One feature request intended to make the flashing process a bit safer was to have a flag in EEPROM which the *bootloader* reads and uses to decide whether it should power on the node controller before running the main program.

The reason for this is that the bootloader is preserved when flashing the rest of the code on the Wagman, so it gives us a way to write a simpler, non-updatable piece to act as a failsafe for flashing the rest of the Wagman code. (For example, if we lost power during a flash, we could possibly be dead...)

**Comment by seanshahkarami** [comment]
Bootloader reference code:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/bootloaders/atmega8

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #18](https://github.com/waggle-sensor/development/issues/18) via [**ZenHub**](https://www.zenhub.com/)
