### ISSUE TITLE
Verify Port Address Mappings

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#2]
This is just a final reminder to walk through a check that all the sensors (thermistors / current sensors / heartbeat) and make sure that they are mapped correctly to the ports.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #27](https://github.com/waggle-sensor/development/issues/27) via [**ZenHub**](https://www.zenhub.com/)
