### ISSUE TITLE
Correct behavior for log messages sent in between commands.

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#4]
The logger current sends some info in between commands run in the Wagman shell. It's not a major issue since they just show up inside another command output but I would like to clean up the behavior of that.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #25](https://github.com/waggle-sensor/development/issues/25) via [**ZenHub**](https://www.zenhub.com/)
