### ISSUE TITLE
Verify Boot Selection Cycle

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#5]
We just need to make sure that the devices are correctly cycled through the primary / secondary boot media on bad starts.

**Comment by seanshahkarami** [comment]
Ok...part of this was me being dumb. I forgot that I temporarily removed the `incrementBootFailures` line when cleaning up the code...

**Comment by seanshahkarami** [comment]
I just extended override boot media command. This should help with testing and also allow the node controller to make some choices about how devices will be started. 😄

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #24](https://github.com/waggle-sensor/development/issues/24) via [**ZenHub**](https://www.zenhub.com/)
