### ISSUE TITLE
Modem Hanging

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/wagman#9]
If the modem hangs, and only a power cycle will correct it, how does that scenario work?

**Comment by seanshahkarami** [comment]
We could have the heartbeat process depend on more conditions being met such as the modem appearing to work, LAN connection showing up, etc.

Alternatively, if the NC detects something like this, it can just request to be reset.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #20](https://github.com/waggle-sensor/development/issues/20) via [**ZenHub**](https://www.zenhub.com/)
